from typing import Protocol
from uuid import UUID
from app.subscriptions.domain.entities import Subscription

class SubscriptionRepositoryProtocol(Protocol):
    async def save(self, subscription: Subscription) -> None: ...
    async def find_by_id(self, subscription_id: UUID) -> Subscription | None : ...
    async def find_active_by_customer(self, customer_name: str) -> Subscription | None : ...
    async def update(self, subscription: Subscription) -> None: ...